#! /bin/bash -e

cd $(dirname $0)/..

docker volume create --name jekyll-apk-cache > /dev/null

docker-compose build ${service-dev}
# docker-compose run --rm ${service-dev} sh -c 'bundle check > /dev/null || bundle install'
docker-compose run --rm --service-ports ${service-dev} "$@"
