#!/bin/bash -e

cd $(dirname $0)/..

command=''

if [ $1 ]; then
  command="proselint $1"
else
  command='find . -maxdepth 1 -name \*.html -not -path "*_site*" -print | xargs proselint'
fi

auto/dev-environment bash -c "$command"
